import { FOCUSKEY } from "@/constants/FocusKeys.ts";

export const channels = ["LOL", "CS2", "HADES", "MW2", "HALO"];

export const CHANNELS = {
  CHANNEL1: "LOL",
  CHANNEL2: "CS2",
  CHANNEL3: "HADES",
  CHANNEL4: "MW2",
  CHANNEL5: "HALO",
};

export const channelToRowMap: Record<string, string> = {
  [CHANNELS.CHANNEL1]: FOCUSKEY.NOW_PLAYING,
  [CHANNELS.CHANNEL2]: FOCUSKEY.NOW_PLAYING,
  [CHANNELS.CHANNEL3]: FOCUSKEY.TRENDING_MOVIES,
  [CHANNELS.CHANNEL4]: FOCUSKEY.POPULAR_TVSHOWS,
  [CHANNELS.CHANNEL5]: FOCUSKEY.POPULAR_TVSHOWS,
};
