export const FOCUSKEY = {
  NAV: "NAV",
  NOW_PLAYING: "NOW_PLAYING",
  TRENDING_MOVIES: "TRENDING_MOVIES",
  POPULAR_TVSHOWS: "POPULAR_TVSHOWS",
  CHANNELWIDGET: "CHANNELWIDGET",
  CARDS: "CARDS",
  HOME_ELEMENTS: "HOME_ELEMENTS",
  MOVIES_PAGE: "MOVIES_PAGE",
  UPCOMING: "UPCOMING",
  DETAILS: "DETAILS",
  BACKBTN: "BACKBTN",
  WATCH_NOWBTN: "WATCH_NOWBTN",
};
